artifacts_root : artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_url: https://github.com/bhuwanjoshi555/Text-Summarizer-Project/raw/main/Samsum%20data.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion
   

